# Generated by Django 3.1.7 on 2021-05-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.AddField(
            model_name='card',
            name='definition',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='card',
            name='word',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
